version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VT_API_KEY=${VT_API_KEY}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ACCOUNT_ID=${CF_ACCOUNT_ID}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: